project_id = "gfpmczssbrnyngaaolpu"

[functions.send-email]
verify_jwt = false

[functions.robots-txt]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.sitemap-xml]
verify_jwt = false

[functions.team-invite]
verify_jwt = false
